apiVersion: apps/v1
kind: Deployment
metadata:
  name: packageserver
  labels:
    app: packageserver
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  # TODO(tflannag): Change back to two replicas
  replicas: 2
  selector:
    matchLabels:
      app: packageserver
  template:
    metadata:
      labels:
        app: packageserver
    spec:
      serviceAccountName: packageserver
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: packageserver
        command:
        - /bin/package-server
        - -v=4
        - --secure-port
        - "5443"
        - --global-namespace
        - olm
        image: quay.io/operator-framework/olm@sha256:b706ee6583c4c3cf8059d44234c8a4505804adcc742bcddb3d1e2f6eff3d6519
        imagePullPolicy: Always
        ports:
        - containerPort: 5443
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5443
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        # securityContext:
        #   # Note(tflannag): This is needed to avoid having to inject certificates ourselves as a
        #   # certificate directory will be created for us.
        #   privileged: true
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
        - mountPath: /apiserver.local.config/certificates
          name: apiservice-cert
        # - mountPath: /tmp/k8s-webhook-server/serving-certs
        #   name: webhook-cert
      volumes:
      - name: tmpfs
      - name: apiservice-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
          secretName: packageserver-serving-cert
      # - name: webhook-cert
      #   secret:
      #     defaultMode: 420
      #     items:
      #     - key: tls.crt
      #       path: tls.crt
      #     - key: tls.key
      #       path: tls.key
      #     secretName: packageserver-service-cert
