name: ci
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          paths_ignore: '["**/*.md"]'

  image:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build the container image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
