name: ci
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        ref: 'master'

    # - name: Build the container image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: Dockerfile
    #     push: false
