name: release
on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get the image tag
        run: |
          # Source: https://github.community/t/how-to-get-just-the-tag-name/16241/32
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo IMAGE_TAG="${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          IMAGE_REPO: ${{ secrets.QUAY_USERNAME }}/olm
          PKG: github.com/operator-framework/operator-lifecycle-manager

      - name: Update OLM CRD manifests
        run: make release ver=${{ env.IMAGE_TAG }} IMAGE_REPO=quay.io/${{ secrets.QUAY_USERNAME }}/olm

      - name: Update release artifacts with rendered Kubernetes manifests
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.IMAGE_TAG }}
          files: |
            deploy/upstream/quickstart/crds.yaml
            deploy/upstream/quickstart/olm.yaml
          draft: true
          token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          repository: timflannagan/operator-lifecycle-manager
